ddqn_agent:
  type: cnn # swin, patch
  sync_every: 1e3
  gamma: 0.99
  replay_memory_size: 5e5
  save_every: 2e5
  exp_rate_max: 0.9
  exp_rate_min: 0.01
  steps_to_explore: 5e6
  learn_every: 3
  burning: 2.5e5
  lr: 1e-5
  batch_size: 32
  sync_every: 3
  save_every: 2e5

dqn_agent:
  type: cnn # swin, patch, cnn, vit
  sync_every: 1e3
  gamma: 0.99
  replay_memory_size: 5e5
  save_every: 2e5
  exp_rate_max: 0.9
  exp_rate_min: 0.01
  steps_to_explore: 5e6
  learn_every: 3
  burning: 2.5e5
  lr: 1e-5
  batch_size: 32
  sync_every: 3
  save_every: 5e5